# Secrets that can be set via files in `./secrets/*.secret`, via coommandline by `--set 'pgAdminUser=xyz,pgHost=host.com,...'` or even uncomment them in the lines below.
# pgAdminUser: ''
# pgHost: ''
# pgPort: ''
# pgPass: ''
# pgPassRO: ''
# pgPassTeam: ''
# esHost: ''
# esPort: ''
# esProto: ''
# esURL: ''
# githubOAuth: ''
#
# You can skip some parts of the deployment (useful when deploying partailly again)
# skipBootstrap (will not run initial bootstrapping - creating logs and users, but you don't need to skip it - bootstrap pod detects already created resources)
# skipCrons (will not create new cronjobs, you should set it when cron jobs are alredy created, if you want to recreate cron jobs, delete existing ones first and do not set this flag)
# skipPV (will not attempt to create persistent volume claim, this is usually needed to avoid creating existing resource)
# skipProvisions (will not create provisioning pods, usually not needed, provisioning pod will detect already provisioned projects and only provision new ones)
# skipSecrets (will not attempt to create secrets, if you want to create new secrets delete current secrets first and do not set this flag)
# skipBootstrap: 1
# skipCrons: 1
# skipPV: 1
# skipProvisions: 1
# skipSecrets: 1
bootstrapCommand: './k8s/deploy_all.sh'
bootstrapLDrop: ''
bootstrapNoCreate: ''
bootstrapPodName: devstats-provision-bootstrap
bootstrapRestartPolicy: Never
bootstrapUDrop: ''
concurrencyPolicy: Forbid
esSecret: es-db
fullnameOverride: devstats
imagePullPolicy: Always
indexProvisionsFrom: 0
indexProvisionsTo: 100
indexCronsFrom: 0
indexCronsTo: 100
name: devstats
nameOverride: devstats
oauthSecret: github-oauth
pgSecret: pg-db
proivisionImage: 'lukaszgryglicki/devstats'
projectsFile: 'k8s/projects.yaml'
provisionCommand: './k8s/deploy_all.sh'
provisionPodName: devstats-provision
pvName: devstats-git
secretType: Opaque
storageAccessModes: ReadWriteMany
storageClass: efs
storageSize: 200Gi
syncCommand: devstats
syncImage: 'lukaszgryglicki/devstats-minimal'
syncPodName: devstats
volumeMountName: data
volumeMountPath: '/root'
volumeName: data
waitForBootstrap: 30
labels:
  name: devstats
projects:
  - proj: iovisor
    db: iovisor
    repo: 'iovisor/bcc'
    cron: '6 * * * *'
  - proj: mininet
    db: mininet
    repo: 'mininet/mininet'
    cron: '7 * * * *'
  - proj: opennetworkinglab
    db: opennetworkinglab
    repo: 'opennetworkinglab/onos'
    cron: '8 * * * *'
  - proj: opensecuritycontroller
    db: opensecuritycontroller
    repo: 'opensecuritycontroller/ocs-core'
    cron: '9 * * * *'
  - proj: openswitch
    db: openswitch
    repo: 'open-switch/opx-nas-interface'
    cron: '10 * * * *'
  - proj: p4lang
    db: p4lang
    repo: 'p4lang/p4c'
    cron: '11 * * * *'
  - proj: openbmp
    db: openbmp
    repo: 'OpenBMP/openbmp'
    cron: '12 * * * *'
  - proj: tungstenfabric
    db: tungstenfabric
    repo: 'tungstenfabric/website'
    cron: '13 * * * *'
  - proj: cord
    db: cord
    repo: 'opencord/voltha'
    cron: '14 * * * *'
  - proj: envoy
    db: envoy
    repo: 'envoyproxy/envoy'
    cron: '15 * * * *'
  - proj: zephyr
    db: zephyr
    repo: 'zephyrproject-rtos/zephyr'
    cron: '16 * * * *'
  - proj: linux
    db: linux
    repo: 'torvalds/linux'
    cron: '17 * * * *'
  - proj: kubernetes
    db: gha
    repo: 'kubernetes/kubernetes'
    cron: '18 * * * *'
  - proj: prometheus
    db: prometheus
    repo: 'prometheus/prometheus'
    cron: '19 * * * *'
  - proj: opentracing
    db: opentracing
    repo: 'opentracing/opentracing-go'
    cron: '20 * * * *'
  - proj: fluentd
    db: fluentd
    repo: 'fluent/fluentd'
    cron: '21 * * * *'
  - proj: linkerd
    db: linkerd
    repo: 'linkerd/linkerd'
    cron: '22 * * * *'
  - proj: grpc
    db: grpc
    repo: 'grpc/grpc'
    cron: '23 * * * *'
  - proj: coredns
    db: coredns
    repo: 'coredns/coredns'
    cron: '24 * * * *'
  - proj: containerd
    db: containerd
    repo: 'containerd/containerd'
    cron: '25 * * * *'
  - proj: rkt
    db: rkt
    repo: 'rkt/rkt'
    cron: '26 * * * *'
  - proj: cni
    db: cni
    repo: 'containernetworking/cni'
    cron: '27 * * * *'
  - proj: jaeger
    db: jaeger
    repo: 'jaegertracing/jaeger'
    cron: '28 * * * *'
  - proj: notary
    db: notary
    repo: 'theupdateframework/notary'
    cron: '29 * * * *'
  - proj: tuf
    db: tuf
    repo: 'theupdateframework/tuf'
    cron: '30 * * * *'
  - proj: rook
    db: rook
    repo: 'rook/rook'
    cron: '31 * * * *'
  - proj: vitess
    db: vitess
    repo: 'vitessio/vitess'
    cron: '32 * * * *'
  - proj: nats
    db: nats
    repo: 'nats-io/gnatsd'
    cron: '33 * * * *'
  - proj: opa
    db: opa
    repo: 'open-policy-agent/opa'
    cron: '34 * * * *'
  - proj: spiffe
    db: spiffe
    repo: 'spiffe/spiffe'
    cron: '35 * * * *'
  - proj: spire
    db: spire
    repo: 'spiffe/spire'
    cron: '36 * * * *'
  - proj: cloudevents
    db: cloudevents
    repo: 'cloudevents/spec'
    cron: '37 * * * *'
  - proj: telepresence
    db: telepresence
    repo: 'telepresenceio/telepresence'
    cron: '38 * * * *'
  - proj: helm
    db: helm
    repo: 'kubernetes/helm'
    cron: '39 * * * *'
  - proj: openmetrics
    db: openmetrics
    repo: 'OpenObservability/OpenMetrics'
    cron: '40 * * * *'
  - proj: harbor
    db: harbor
    repo: 'goharbor/harbor'
    cron: '41 * * * *'
  - proj: etcd
    db: etcd
    repo: 'etcd-io/etcd'
    cron: '42 * * * *'
  - proj: tikv
    db: tikv
    repo: 'tikv/tikv'
    cron: '43 * * * *'
  - proj: cortex
    db: cortex
    repo: 'cortexproject/cortex'
    cron: '44 * * * *'
  - proj: buildpacks
    db: buildpacks
    repo: 'buildpack/lifecycle'
    cron: '45 * * * *'
  - proj: falco
    db: falco
    repo: 'falcosecurity/falco'
    cron: '46 * * * *'
  - proj: dragonfly
    db: dragonfly
    repo: 'dragonflyoss/Dragonfly'
    cron: '47 * * * *'
  - proj: virtualkubelet
    db: virtualkubelet
    repo: 'virtual-kubelet/virtual-kubelet'
    cron: '48 * * * *'
  - proj: cncf
    db: cncf
    repo: 'cncf/landscape'
    cron: '49 * * * *'
  - proj: opencontainers
    db: opencontainers
    repo: 'opencontainers/runc'
    cron: '50 * * * *'
  - proj: istio
    db: istio
    repo: 'istio/istio'
    cron: '51 * * * *'
  - proj: spinnaker
    db: spinnaker
    repo: 'spinnaker/spinnaker'
    cron: '52 * * * *'
  - proj: knative
    db: knative
    repo: 'knative/serving'
    cron: '53 * * * *'
