name: devstats
nameOverride: devstats
fullnameOverride: devstats
labels:
  name: devstats
pvName: devstats-git
storageClass: efs
storageAccessModes: ReadWriteMany
storageSize: 200Gi
pgSecret: pg-db
esSecret: es-db
oauthSecret: github-oauth
secretType: Opaque
bootstrapUDrop: ''
bootstrapLDrop: ''
bootstrapNoCreate: ''
bootstrapPodName: devstats-provision-bootstrap
bootstrapCommand: './k8s/deploy_all.sh'
proivisionImage: 'lukaszgryglicki/devstats'
imagePullPolicy: Always
volumeMountName: data
volumeMountPath: '/root'
volumeName: data
bootstrapRestartPolicy: Never
provisionPodName: devstats-provision
provisionCommand: './k8s/deploy_all.sh'
syncPodName: devstats
concurrencyPolicy: Forbid
syncCommand: devstats
projectsFile: 'k8s/projects.yaml'
syncImage: 'lukaszgryglicki/devstats-minimal'
projects:
  - proj: iovisor
    db: iovisor
    repo: 'iovisor/bcc'
    cron: '6 * * * *'
  - proj: mininet
    db: mininet
    repo: 'mininet/mininet'
    cron: '10 * * * *'
  - proj: opennetworkinglab
    db: opennetworkinglab
    repo: 'opennetworkinglab/onos'
    cron: '14 * * * *'
  - proj: opensecuritycontroller
    db: opensecuritycontroller
    repo: 'opensecuritycontroller/ocs-core'
    cron: '18 * * * *'
  - proj: openswitch
    db: openswitch
    repo: 'open-switch/opx-nas-interface'
    cron: '22 * * * *'
  - proj: p4lang
    db: p4lang
    repo: 'p4lang/p4c'
    cron: '26 * * * *'
  - proj: openbmp
    db: openbmp
    repo: 'OpenBMP/openbmp'
    cron: '30 * * * *'
  - proj: tungstenfabric
    db: tungstenfabric
    repo: 'tungstenfabric/website'
    cron: '34 * * * *'
  - proj: cord
    db: cord
    repo: 'opencord/voltha'
    cron: '38 * * * *'
  - proj: envoy
    db: envoy
    repo: 'envoyproxy/envoy'
    cron: '42 * * * *'
  - proj: zephyr
    db: zephyr
    repo: 'zephyrproject-rtos/zephyr'
    cron: '46 * * * *'
  - proj: linux
    db: linux
    repo: 'torvalds/linux'
    cron: '50 * * * *'
