# Secrets that can be set via files in `./secrets/*.secret`, via coommandline by `--set 'pgAdminUser=xyz,pgHost=host.com,...'` or even uncomment them in the lines below.
# pgAdminUser: ''
# pgHost: ''
# pgPort: ''
# pgPass: ''
# pgPassRO: ''
# pgPassTeam: ''
# esHost: ''
# esPort: ''
# esProto: ''
# esURL: ''
# githubOAuth: ''
# grafanaUser: ''
# grafanaPassword: ''
#
# You can skip some parts of the deployment (useful when deploying partailly again)
# skipBootstrap (will not run initial bootstrapping - creating logs and users, but you don't need to skip it - bootstrap pod detects already created resources)
# skipCrons (will not create new cronjobs, you should set it when cron jobs are alredy created, if you want to recreate cron jobs, delete existing ones first and do not set this flag)
# skipGrafanas (will not create Grafana deployments)
# skipPV (will not attempt to create persistent volume claim, this is usually needed to avoid creating existing resource)
# skipProvisions (will not create provisioning pods, usually not needed, provisioning pod will detect already provisioned projects and only provision new ones)
# skipSecrets (will not attempt to create secrets, if you want to create new secrets delete current secrets first and do not set this flag)
# skipBootstrap: 1
# skipCrons: 1
# skipGrafanas: 1
# skipPV: 1
# skipProvisions: 1
# skipSecrets: 1
#
# You can overwrite the number of CPU autodetected in each pod, setting thsi to 1 will make each pod single-threaded
# nCPUs: 0
#
# Other evrironment options
# bootstrapCommandArgs:
#   - "bootarg"
# cmdDebug: 1
# debug: 1
# forceComputeAll: 1
# githubDebug: 1
# grafanaCommandArgs:
#   - arg1
#   - arg2
# limitsCPU: 8
# limitsMemory: '32Gi'
# onlyMetrics: 'events,tz'
# periods: 'd7:t,m:f,q:t,y10:f'
# provisionCommand: 'sleep'
# provisionCommandArgs:
#   - "36000"
# queryOut: 1
# reposDir: "/root/devstats_repos/"
# requestsCPU: 2
# requestsMemory: '16Gi'
# skipMetrics: 'users_activity,committers_cum'
# syncCommandArgs:
#   - "syncarg"
# useResourcesLimits: 1
affiliations: 'github_users.json'
bootstrapCommand: './k8s/deploy_all.sh'
bootstrapLDrop: ''
bootstrapNoCreate: ''
bootstrapPodName: devstats-provision-bootstrap
bootstrapRestartPolicy: Never
bootstrapUDrop: ''
companyAcq: "companies.yaml"
concurrencyPolicy: Forbid
esSecret: es-db
esBulkSize: 5000
fullnameOverride: devstats
grafanaCommand: 'grafana_start.sh'
grafanaImage: 'lukaszgryglicki/devstats-grafana'
grafanaNReplicas: 1
grafanaPodName: devstats-grafana
grafanaPort: 3000
grafanaRestartPolicy: Always
grafanaSecret: grafana-secret
imagePullPolicy: Always
indexCronsFrom: 0
indexCronsTo: 100
indexGrafanasFrom: 0
indexGrafanasTo: 100
indexProvisionsFrom: 0
indexProvisionsTo: 100
name: devstats
nameOverride: devstats
oauthSecret: github-oauth
pgSecret: pg-db
proivisionImage: 'lukaszgryglicki/devstats'
projectsFile: 'k8s/projects.yaml'
provisionCommand: './k8s/deploy_all.sh'
provisionPodName: devstats-provision
pvName: devstats-git
secretType: Opaque
storageAccessModes: ReadWriteMany
storageClass: efs
storageSize: 200Gi
syncCommand: devstats
syncImage: 'lukaszgryglicki/devstats-minimal'
syncPodName: devstats
volumeMountName: data
volumeMountPath: '/root'
volumeName: data
useES: 1
useESRaw: 1
waitForBootstrap: 30
labels:
  name: devstats
nodeSelector:
  lfda: grimoire
projects:
  - proj: iovisor
    db: iovisor
    icon: 'cncf'
    org: 'IO Visort'
    repo: 'iovisor/bcc'
    cron: '5 * * * *'
  - proj: mininet
    db: mininet
    icon: 'cncf'
    org: 'Mininet'
    repo: 'mininet/mininet'
    cron: '5 * * * *'
  - proj: opennetworkinglab
    db: opennetworkinglab
    icon: 'cncf'
    org: 'Open Networking Laboratory'
    repo: 'opennetworkinglab/onos'
    cron: '6 * * * *'
  - proj: opensecuritycontroller
    db: opensecuritycontroller
    icon: 'cncf'
    org: 'Open Security Controller'
    repo: 'opensecuritycontroller/ocs-core'
    cron: '6 * * * *'
  - proj: openswitch
    db: openswitch
    icon: 'cncf'
    org: 'OpenSwitch'
    repo: 'open-switch/opx-nas-interface'
    cron: '7 * * * *'
  - proj: p4lang
    db: p4lang
    icon: 'cncf'
    org: 'P4 Language'
    repo: 'p4lang/p4c'
    cron: '7 * * * *'
  - proj: openbmp
    db: openbmp
    icon: 'cncf'
    org: 'OpenBMP'
    repo: 'OpenBMP/openbmp'
    cron: '8 * * * *'
  - proj: tungstenfabric
    db: tungstenfabric
    icon: 'cncf'
    org: 'Tungsten fabric'
    repo: 'tungstenfabric/website'
    cron: '8 * * * *'
  - proj: cord
    db: cord
    icon: 'cncf'
    org: 'CORD'
    repo: 'opencord/voltha'
    cron: '9 * * * *'
  - proj: envoy
    db: envoy
    icon: 'envoy'
    org: 'Envoy'
    repo: 'envoyproxy/envoy'
    cron: '9 * * * *'
  - proj: zephyr
    db: zephyr
    icon: 'cncf'
    org: 'Zephyr'
    repo: 'zephyrproject-rtos/zephyr'
    cron: '11 * * * *'
  - proj: linux
    db: linux
    icon: 'cncf'
    org: 'linux'
    repo: 'torvalds/linux'
    cron: '12 * * * *'
  - proj: kubernetes
    db: gha
    icon: 'k8s'
    org: 'Kubernetes'
    repo: 'kubernetes/kubernetes'
    cron: '13 * * * *'
  - proj: prometheus
    db: prometheus
    icon: 'prometheus'
    org: 'Prometheus'
    repo: 'prometheus/prometheus'
    cron: '18 * * * *'
  - proj: opentracing
    db: opentracing
    icon: 'opentracing'
    org: 'OpenTracing'
    repo: 'opentracing/opentracing-go'
    cron: '20 * * * *'
  - proj: fluentd
    db: fluentd
    icon: 'fluentd'
    org: 'Fluentd'
    repo: 'fluent/fluentd'
    cron: '21 * * * *'
  - proj: linkerd
    db: linkerd
    icon: 'linkerd'
    org: 'Linkerd'
    repo: 'linkerd/linkerd'
    cron: '22 * * * *'
  - proj: grpc
    db: grpc
    icon: 'grpc'
    org: 'gRPC'
    repo: 'grpc/grpc'
    cron: '23 * * * *'
  - proj: coredns
    db: coredns
    icon: 'coredns'
    org: 'CoreDNS'
    repo: 'coredns/coredns'
    cron: '25 * * * *'
  - proj: containerd
    db: containerd
    icon: 'containerd'
    org: 'containerd'
    repo: 'containerd/containerd'
    cron: '26 * * * *'
  - proj: rkt
    db: rkt
    icon: 'rkt'
    org: 'rkt'
    repo: 'rkt/rkt'
    cron: '26 * * * *'
  - proj: cni
    db: cni
    icon: 'cni'
    org: 'CNI'
    repo: 'containernetworking/cni'
    cron: '27 * * * *'
  - proj: jaeger
    db: jaeger
    icon: 'jaeger'
    org: 'Jaeger'
    repo: 'jaegertracing/jaeger'
    cron: '28 * * * *'
  - proj: notary
    db: notary
    icon: 'notary'
    org: 'Notary'
    repo: 'theupdateframework/notary'
    cron: '29 * * * *'
  - proj: tuf
    db: tuf
    icon: 'tuf'
    org: 'TUF'
    repo: 'theupdateframework/tuf'
    cron: '29 * * * *'
  - proj: rook
    db: rook
    icon: 'rook'
    org: 'Rook'
    repo: 'rook/rook'
    cron: '31 * * * *'
  - proj: vitess
    db: vitess
    icon: 'vitess'
    org: 'Vitess'
    repo: 'vitessio/vitess'
    cron: '31 * * * *'
  - proj: nats
    db: nats
    icon: 'nats'
    org: 'NATS'
    repo: 'nats-io/gnatsd'
    cron: '32 * * * *'
  - proj: opa
    db: opa
    icon: 'opa'
    org: 'OPA'
    repo: 'open-policy-agent/opa'
    cron: '32 * * * *'
  - proj: spiffe
    db: spiffe
    icon: 'spiffe'
    org: 'Spiffe'
    repo: 'spiffe/spiffe'
    cron: '33 * * * *'
  - proj: spire
    db: spire
    icon: 'spire'
    org: 'Spire'
    repo: 'spiffe/spire'
    cron: '33 * * * *'
  - proj: cloudevents
    db: cloudevents
    icon: 'cloudevents'
    org: 'CloudEvents'
    repo: 'cloudevents/spec'
    cron: '33 * * * *'
  - proj: telepresence
    db: telepresence
    icon: 'telepresence'
    org: 'Telepresence'
    repo: 'telepresenceio/telepresence'
    cron: '34 * * * *'
  - proj: helm
    db: helm
    icon: 'helm'
    org: 'Helm'
    repo: 'kubernetes/helm'
    cron: '34 * * * *'
  - proj: openmetrics
    db: openmetrics
    icon: 'openmetrics'
    org: 'OpenMetrics'
    repo: 'OpenObservability/OpenMetrics'
    cron: '36 * * * *'
  - proj: harbor
    db: harbor
    icon: 'harbor'
    org: 'Harbor'
    repo: 'goharbor/harbor'
    cron: '36 * * * *'
  - proj: etcd
    db: etcd
    icon: 'etcd'
    org: 'etcd'
    repo: 'etcd-io/etcd'
    cron: '37 * * * *'
  - proj: tikv
    db: tikv
    icon: 'tikv'
    org: 'TiKV'
    repo: 'tikv/tikv'
    cron: '38 * * * *'
  - proj: cortex
    db: cortex
    icon: 'cortex'
    org: 'Cortex'
    repo: 'cortexproject/cortex'
    cron: '38 * * * *'
  - proj: buildpacks
    db: buildpacks
    icon: 'buildpacks'
    org: 'Buildpacks'
    repo: 'buildpack/lifecycle'
    cron: '39 * * * *'
  - proj: falco
    db: falco
    icon: 'falco'
    org: 'Falco'
    repo: 'falcosecurity/falco'
    cron: '39 * * * *'
  - proj: dragonfly
    db: dragonfly
    icon: 'dragonfly'
    org: 'Dragonfly'
    repo: 'dragonflyoss/Dragonfly'
    cron: '40 * * * *'
  - proj: virtualkubelet
    db: virtualkubelet
    icon: 'virtualkubelet'
    org: 'Virtual Kubelet'
    repo: 'virtual-kubelet/virtual-kubelet'
    cron: '40 * * * *'
  - proj: cncf
    db: cncf
    icon: 'cncf'
    org: 'CNCF'
    repo: 'cncf/landscape'
    cron: '41 * * * *'
  - proj: opencontainers
    db: opencontainers
    icon: 'opencontainers'
    org: 'OCI'
    repo: 'opencontainers/runc'
    cron: '41 * * * *'
  - proj: istio
    db: istio
    icon: 'cncf'
    org: 'Istio'
    repo: 'istio/istio'
    cron: '42 * * * *'
  - proj: spinnaker
    db: spinnaker
    icon: 'spinnaker'
    org: 'Spinnaker'
    repo: 'spinnaker/spinnaker'
    cron: '43 * * * *'
  - proj: knative
    db: knative
    icon: 'cncf'
    org: 'Knative'
    repo: 'knative/serving'
    cron: '44 * * * *'
