bootstrapCommand: './k8s/deploy_all.sh'
bootstrapLDrop: ''
bootstrapNoCreate: ''
bootstrapPodName: devstats-provision-bootstrap
bootstrapRestartPolicy: Never
bootstrapUDrop: ''
concurrencyPolicy: Forbid
esSecret: es-db
fullnameOverride: devstats
imagePullPolicy: Always
name: devstats
nameOverride: devstats
oauthSecret: github-oauth
pgSecret: pg-db
proivisionImage: 'lukaszgryglicki/devstats'
projectsFile: 'k8s/projects.yaml'
provisionCommand: './k8s/deploy_all.sh'
provisionPodName: devstats-provision
pvName: devstats-git
secretType: Opaque
storageAccessModes: ReadWriteMany
storageClass: efs
storageSize: 200Gi
syncCommand: devstats
syncImage: 'lukaszgryglicki/devstats-minimal'
syncPodName: devstats
volumeMountName: data
volumeMountPath: '/root'
volumeName: data
waitForBootstrap: 30
labels:
  name: devstats
projects:
  - proj: iovisor
    db: iovisor
    repo: 'iovisor/bcc'
    cron: '6 * * * *'
  - proj: mininet
    db: mininet
    repo: 'mininet/mininet'
    cron: '10 * * * *'
  - proj: opennetworkinglab
    db: opennetworkinglab
    repo: 'opennetworkinglab/onos'
    cron: '14 * * * *'
  - proj: opensecuritycontroller
    db: opensecuritycontroller
    repo: 'opensecuritycontroller/ocs-core'
    cron: '18 * * * *'
  - proj: openswitch
    db: openswitch
    repo: 'open-switch/opx-nas-interface'
    cron: '22 * * * *'
  - proj: p4lang
    db: p4lang
    repo: 'p4lang/p4c'
    cron: '26 * * * *'
  - proj: openbmp
    db: openbmp
    repo: 'OpenBMP/openbmp'
    cron: '30 * * * *'
  - proj: tungstenfabric
    db: tungstenfabric
    repo: 'tungstenfabric/website'
    cron: '34 * * * *'
  - proj: cord
    db: cord
    repo: 'opencord/voltha'
    cron: '38 * * * *'
  - proj: envoy
    db: envoy
    repo: 'envoyproxy/envoy'
    cron: '42 * * * *'
  - proj: zephyr
    db: zephyr
    repo: 'zephyrproject-rtos/zephyr'
    cron: '46 * * * *'
  - proj: linux
    db: linux
    repo: 'torvalds/linux'
    cron: '50 * * * *'
# Secrets that can be set via files in `./secrets/*.secret`, via coommandline by `--set 'pgAdminUser=xyz,pgHost=host.com,...'` or even uncomment them in the lines below.
# pgAdminUser: ''
# pgHost: ''
# pgPort: ''
# pgPass: ''
# pgPassRO: ''
# pgPassTeam: ''
# esHost: ''
# esPort: ''
# esProto: ''
# esURL: ''
# githubOAuth: ''
