apiVersion: v1
kind: Pod
metadata:
  name: "devstats-minimal-${TIMESTAMP}"
spec:
  containers:
  - command:
    - /bin/bash
    env:
    - name: ONLY
      value: "${ONLY}"
    - name: PG_HOST
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_HOST.secret
    - name: GHA2DB_USE_ES
      value: "1"
    - name: GHA2DB_GITHUB_OAUTH
      valueFrom:
        secretKeyRef:
          name: github-oauth
          key: GHA2DB_GITHUB_OAUTH.secret
    - name: PG_PORT
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_PORT.secret
    - name: GHA2DB_USE_ES_RAW
      value: "1"
    - name: GHA2DB_ES_URL
      valueFrom:
        secretKeyRef:
          name: es-db
          key: GHA2DB_ES_URL.secret
    - name: GHA2DB_PROPAGATE_ONLY_VAR
      value: "1"
    - name: GHA2DB_PROJECTS_YAML
      value: k8s/projects.yaml
    - name: PG_PASS
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_PASS.secret
    image: lukaszgryglicki/devstats-minimal
    imagePullPolicy: Always
    name: "devstats-minimal-${TIMESTAMP}"
    stdin: true
    stdinOnce: true
    tty: true
    volumeMounts:
    - name: data
      mountPath: /root
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: devstats-git
  restartPolicy: Never
