apiVersion: v1
kind: Pod
metadata:
  name: "devstats-test-${TIMESTAMP}"
spec:
  containers:
  - command:
    - /bin/bash
    env:
    - name: AWS_PROFILE
      value: "${AWS_PROFILE}"
    - name: PG_HOST
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_HOST.secret
    - name: PG_PORT
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_PORT.secret
    - name: PG_PASS
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_PASS.secret
    - name: ES_PORT
      valueFrom:
        secretKeyRef:
          name: es-db
          key: ES_PORT.secret
    - name: ES_HOST
      valueFrom:
        secretKeyRef:
          name: es-db
          key: ES_HOST.secret
    - name: ES_PROTO
      valueFrom:
        secretKeyRef:
          name: es-db
          key: ES_PROTO.secret
    - name: GHA2DB_ES_URL
      valueFrom:
        secretKeyRef:
          name: es-db
          key: GHA2DB_ES_URL.secret
    - name: GHA2DB_GITHUB_OAUTH
      valueFrom:
        secretKeyRef:
          name: github-oauth
          key: GHA2DB_GITHUB_OAUTH.secret
    image: lukaszgryglicki/devstats
    imagePullPolicy: Always
    name: "devstats-test-${TIMESTAMP}"
    stdin: true
    stdinOnce: true
    tty: true
  restartPolicy: Never
