# Secrets that can be set via files in `./secrets/*.secret`, via coommandline by `--set 'shUser=xyz,shHost=host.com,...'` or even uncomment them in the lines below.
# shUser: ''
# shHost: ''
# shPort: ''
# shPass: ''
# shDB: ''
#
# You can skip some parts of the deployment (useful when deploying partailly again)
# skipCron (will not create a new cron job, you should set it when cron job is already created, if you want to recreate a cron job, delete the existing one first and do not set this flag)
# skipSecrets (will not attempt to create secrets, if you want to create new secrets delete current secrets first and do not set this flag)
# skipSHSecret (will skip creating SH (sorting hat) secret)
# skipCron: 1
# skipSecrets: 1
#
# Other json2hat params (see NOTES.txt):
# shDSN: 'shuser:shpassword@tcp(shhost:shport)/shdb?charset=utf8'
# shProto: tcp
# shParams: '?charset=utf8'
# shCleanup: 1
# shTestConnect: 1
# shRemoteJSONPath: 'https://raw.githubusercontent.com/cncf/devstats/master/github_users.json'
# shRemoteYAMLPath: 'https://raw.githubusercontent.com/cncf/devstats/master/companies.yaml'
#
# Other evrironment options:
# importCommandArgs:
#   - "bootarg"
# limitsCPU: 8
# limitsMemory: '32Gi'
# requestsCPU: 2
# requestsMemory: '16Gi'
# useResourcesLimits: 1
fullnameOverride: json2hat
imagePullPolicy: Always
importCommand: 'json2hat'
importImage: 'lukaszgryglicki/json2hat'
importPodName: json2hat
name: json2hat
nameOverride: json2hat
secretType: Opaque
shSecret: sh-db
labels:
  name: json2hat
nodeSelector:
  lfda: grimoire
