---
language: go
go:
  - 1.10.1
before_install:
  - go get -u github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/jgautheron/goconst/cmd/goconst
  - go get github.com/jgautheron/usedexports
  - go get github.com/kisielk/errcheck
  - go get github.com/google/go-github/github
  - go get github.com/lib/pq
  - go get golang.org/x/oauth2
  - sudo -u postgres createdb gha
  - sudo -u postgres psql gha -c "create user gha_admin with password 'pwd';"
  - sudo -u postgres psql gha -c 'grant all privileges on database "gha" to gha_admin;'
  - sudo -u postgres psql gha -c "alter user gha_admin createdb;"
script:
  - mv /home/travis/gopath/src/github.com/cncf/devstats /home/travis/gopath/src/devstats
  - cd /home/travis/gopath/src/devstats
  - make
  - make test
  - GHA2DB_PROJECT=kubernetes PG_PASS=pwd ./dbtest.sh
services:
  - postgresql
addons:
  postgresql: "9.6"
notifications:
  webhooks:
    - https://cncftest.io:2982/hook
    - https://devstats.cncf.io:2982/hook
