language: go
go:
  - 1.9
before_install:
  - go get -u github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/jgautheron/goconst/cmd/goconst
  - go get github.com/jgautheron/usedexports
  - go get github.com/influxdata/influxdb/client/v2
  - go get github.com/lib/pq
  - go get golang.org/x/text/transform
  - go get golang.org/x/text/unicode/norm
  - go get gopkg.in/yaml.v2
  - sudo -u postgres createdb gha
  - sudo -u postgres psql gha -c "create user gha_admin with password 'pwd';"
  - sudo -u postgres psql gha -c 'grant all privileges on database "gha" to gha_admin;'
  - sudo -u postgres psql gha -c "alter user gha_admin createdb;"
  - curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
  - source /etc/lsb-release
  - echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
  - sudo apt-get update
  - sudo apt-get install influxdb
  - sudo service influxdb start
script:
  - mv /home/travis/gopath/src/github.com/cncf/gha2db /home/travis/gopath/src/gha2db
  - cd /home/travis/gopath/src/gha2db
  - make
  - make test
  - PG_PASS=pwd ./dbtest.sh
services:
  - postgresql
addons:
  postgresql: "9.6"
notifications:
  webhooks: http://cncftest.io:1982/hook
