---
columns:
  - table_regexp: '^ssig_pr_wl'
    tag: tsig_mentions_labels
    column: sig_mentions_labels_name
  - table_regexp: '^sgh_stats_rgrp$'
    tag: trepo_groups
    column: repo_group_name
  - table_regexp: '^spr_appr'
    tag: trepo_groups
    column: repo_group_name
  - table_regexp: '^sgh_stats_r$'
    tag: ttop_repo_names
    column: top_repo_names_name
  - table_regexp: '^sbot_commands$'
    tag: tbot_commands
    column: bot_command_name
  - table_regexp: '^scompany_activity$'
    tag: tcompanies
    column: companies_name
  - table_regexp: '^suser_reviews$'
    tag: treviewers
    column: reviewers_name
  - table_regexp: '^ssigm_txt$'
    tag: tsig_mentions_texts
    column: sig_mentions_texts_name
  - table_regexp: '^sprblck'
    tag: tall_repo_groups
    column: all_repo_group_name
