---
metrics:
  - name: Company statistics by repository groups
    series_name_or_func: multi_row_multi_column
    sqls: [company_activity, company_activity_commits]
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: company_activity
  - name: Number of companies and developers contributing
    series_name_or_func: multi_row_multi_column
    sql: num_stats
    periods: d,w,m,q
    aggregate: 1,7,28
    skip: d,w7,m7,q7,w28,m28,q28
    merge_series: num_stats
  - name: Company summaries
    sql: project_company_stats
    series_name_or_func: multi_row_single_column
    histogram: true
    annotations_ranges: true
    merge_series: hcom
  - name: Gender stats
    series_name_or_func: multi_row_multi_column
    sqls: [gender, committers_gender]
    periods: w,m,q,y
    multi_value: true
    merge_series: sex
  - name: Gender stats cumulative
    series_name_or_func: multi_row_multi_column
    sqls: [gender_cum, committers_gender_cum]
    periods: m
    multi_value: true
    merge_series: sexcum
  - name: Countries stats
    series_name_or_func: multi_row_multi_column
    sqls: [countries, committers_countries]
    periods: w,m,q,y
    multi_value: true
    merge_series: countries
  - name: Countries stats cumulative
    series_name_or_func: multi_row_multi_column
    sqls: [countries_cum, committers_countries_cum]
    periods: m
    multi_value: true
    merge_series: countriescum
  - name: Timezone stats
    series_name_or_func: multi_row_multi_column
    sqls: [tz, committers_tz]
    periods: h,d,w,m,q,y
    aggregate: 1,7
    skip: h7,w7,m7,q7,y7
    multi_value: true
    merge_series: tz
  - name: Company PRs in repository groups
    sql: company_prs
    series_name_or_func: company_prs
    histogram: true
    annotations_ranges: true
