---
metrics:
  - name: Activity repo groups
    series_name_or_func: multi_row_single_column
    sql: activity_repo_groups
    periods: h,d,w,m,q,y
    aggregate: 1,7,24
    skip: h7,w7,m7,q7,y7,d24,w24,m24,q24,y24
    multi_value: true
  - name: Commits repo groups
    series_name_or_func: multi_row_single_column
    sql: commits_repo_groups
    periods: h,d,w,m,q,y
    aggregate: 1,7,24
    skip: h7,w7,m7,q7,y7,d24,w24,m24,q24,y24
    multi_value: true
  - name: All PRs merged
    add_period_to_name: true
    series_name_or_func: all_prs_merged
    sql: all_prs_merged
    periods: h,d,w,m,q,y
    aggregate: 1,2,3,4,7,12
    skip: w7,w12,m7,q4,q7,q12,y4,y7,y12
  - name: SIG mentions breakdown by categories using text
    series_name_or_func: multi_row_single_column
    sql: sig_mentions_breakdown
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: PRs labels by repository groups
    series_name_or_func: multi_row_single_column
    sql: prs_labels
    periods: d
    multi_value: true
  - name: Time opened to merged (number of hours)
    series_name_or_func: multi_row_multi_column
    sql: opened_to_merged
    periods: d,w,m,q,y
    desc: time_diff_as_string
  - name: PRs opened -> lgtmed -> approved -> merged (numer of hours)
    series_name_or_func: multi_row_multi_column
    sql: time_metrics
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    desc: time_diff_as_string
  - name: Suggested PR reviewers
    series_name_or_func: multi_row_multi_column
    sql: other_approver
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
  - name:
      "Time before any comments or activities from someone other \
       than the author"
    series_name_or_func: multi_row_multi_column
    sql: first_non_author_activity
    periods: w,m,q,y
    desc: time_diff_as_string
  - name: Opened PRs age and count
    series_name_or_func: multi_row_multi_column
    sql: prs_age
    periods: d,w,m,q,y
    aggregate: 1,3,7
    skip: m7,q3,q7,y3,y7
    desc: time_diff_as_string
  - name: Closed Issues age and count
    series_name_or_func: multi_row_multi_column
    sql: issues_age
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    desc: time_diff_as_string
  - name: PR comments percentiles
    series_name_or_func: single_row_multi_column
    sql: pr_comments
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
  - name: Stargazers, watchers, forks
    series_name_or_func: multi_row_multi_column
    sql: watchers
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
  - name: New contributors
    series_name_or_func: multi_row_multi_column
    sql: new_contributors
    periods: d,w,m,q,y
  - name: Episodic contributors
    series_name_or_func: multi_row_multi_column
    sql: episodic_contributors
    periods: d,w,m,q,y
  - name: New issues
    series_name_or_func: multi_row_multi_column
    sql: new_issues
    periods: d,w,m,q,y
  - name: Episodic issues
    series_name_or_func: multi_row_multi_column
    sql: episodic_issues
    periods: d,w,m,q,y
  - name: SIG mentions using labels
    series_name_or_func: multi_row_single_column
    sql: labels_sig
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: KIND mentions using labels
    series_name_or_func: multi_row_single_column
    sql: labels_kind
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: SIG KIND mentions using labels
    series_name_or_func: multi_row_single_column
    sql: labels_sig_kind
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: Issues closed broken down by SIG and kind
    series_name_or_func: multi_row_single_column
    sql: labels_sig_kind_closed
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: Issues opened broken down by repo group
    series_name_or_func: multi_row_single_column
    sql: issues_opened
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: Issues closed broken down by repo group
    series_name_or_func: multi_row_single_column
    sql: issues_closed
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: Bot commands usage
    series_name_or_func: multi_row_single_column
    sql: bot_commands
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: Reviewers
    series_name_or_func: multi_row_single_column
    sql: reviewers
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
  - name: Reviewers histogram
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: hist_reviewers
  - name: Open issues by milestone
    series_name_or_func: multi_row_single_column
    sql: open_issues_sigs_milestones
    periods: d
  - name: Open PRs by milestone
    series_name_or_func: multi_row_single_column
    sql: open_prs_sigs_milestones
    periods: d
  - name: Most active commenters
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: hist_commenters
  - name: Approvers histogram
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: hist_approvers
  - name: PR authors histogram
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: hist_pr_authors
  - name: PR authors companies histogram
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: hist_pr_companies
  - name: Project stats
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: project_stats
  - name: Company summaries
    sql: project_company_stats
    series_name_or_func: multi_row_single_column
    histogram: true
    annotations_ranges: true
  - name: Developer summaries
    sql: project_developer_stats
    series_name_or_func: multi_row_single_column
    histogram: true
    annotations_ranges: true
  - name: PR workload tabular
    sql: pr_workload_table
    series_name_or_func: multi_row_multi_column
    histogram: true
    annotations_ranges: true
    multi_value: true
  - name: PR workload chart
    series_name_or_func: multi_row_multi_column
    sql: pr_workload
    periods: d
    multi_value: true
  - name: Repository comments
    series_name_or_func: multi_row_single_column
    sql: repo_comments
    periods: d,w,m,q,y
    aggregate: 1,3,7
    skip: m7,q3,q7,y3,y7
  - name: Repository commenters
    series_name_or_func: multi_row_single_column
    sql: repo_commenters
    periods: d,w,m,q,y
    aggregate: 1,3,7
    skip: m7,q3,q7,y3,y7
  - name: New pull requests opened per repository
    series_name_or_func: multi_row_single_column
    sql: new_prs
    periods: d,w,m,q,y
    aggregate: 1,3,7
    skip: m7,q3,q7,y3,y7
  - name: Pull requests unique authors per repository
    series_name_or_func: multi_row_single_column
    sql: prs_authors
    periods: d,w,m,q,y
    aggregate: 1,3,7
    skip: m7,q3,q7,y3,y7
  - name: SIG mentions using texts
    series_name_or_func: multi_row_single_column
    sql: sig_mentions
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: SIG mentions categories using texts
    series_name_or_func: multi_row_single_column
    sql: sig_mentions_cats
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: PRs merged per repo
    series_name_or_func: multi_row_single_column
    sql: prs_merged
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: PRs merged per repo groups
    series_name_or_func: multi_row_single_column
    sql: prs_merged_groups
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: PRs approved and awaiting approval
    series_name_or_func: multi_row_multi_column
    sql: prs_state
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: d,w7,m7,q7,y7
    multi_value: true
  - name: PRs blocked for various reasons
    series_name_or_func: multi_row_multi_column
    sql: prs_blocked
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: d,w7,m7,q7,y7
    multi_value: true
  - name: Companies stats & velocity
    series_name_or_func: multi_row_multi_column
    sql: company_activity
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: Number of companies and developers contributing
    series_name_or_func: multi_row_multi_column
    sql: num_stats
    periods: d,w,m,q
    aggregate: 3,4,6,7,14
    skip: d3,d4,d6,w3,w6,w7,w14,m7,m14,q3,q6,q7,q14
  - name: Approvers in repository groups
    series_name_or_func: multi_row_single_column
    sql: approvers
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: User reviews
    series_name_or_func: multi_row_single_column
    sql: reviews_per_user
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: OWNERS file
    series_name_or_func: owners_d
    sql: owners
    periods: d
  - name: GitHub activity
    series_name_or_func: events_h
    sql: events
    periods: h
