---
metrics:
  - name: Github Stats by Repository Group
    series_name_or_func: multi_row_single_column
    sql: github_stats_by_repo_groups
    periods: h,d,w,m,q,y
    aggregate: 1,7,24
    skip: h7,w7,m7,q7,y7,d24,w24,m24,q24,y24
    multi_value: true
    merge_series: gh_stats_rgrp
  - name: Github Stats by Repository
    series_name_or_func: multi_row_single_column
    sql: github_stats_by_repos
    periods: h,d,w,m,q,y
    aggregate: 1,7,24
    skip: h7,w7,m7,q7,y7,d24,w24,m24,q24,y24
    multi_value: true
    merge_series: gh_stats_r
  - name: PR labels repository groups
    series_name_or_func: multi_row_single_column
    sql: prs_labels
    periods: d
    merge_series: prs_labels
  - name: PR Time to Approve and Merge
    series_name_or_func: multi_row_multi_column
    sql: time_metrics
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    desc: time_diff_as_string
    merge_series: time_metrics
  - name: PR time to engagement
    series_name_or_func: multi_row_multi_column
    sql: first_non_author_activity
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: d,w7,m7,q7,y7
    desc: time_diff_as_string
    merge_series: first_non_author
  - name: Opened PRs age by repository group
    series_name_or_func: multi_row_multi_column
    sql: prs_age
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    desc: time_diff_as_string
    merge_series: prs_age
  - name: Issues age by SIG and repository group
    series_name_or_func: multi_row_multi_column
    sql: issues_age
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    desc: time_diff_as_string
    merge_series: issues_age
  - name: PR comments
    series_name_or_func: single_row_multi_column
    sql: pr_comments
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
  - name: Stars and forks by repository
    series_name_or_func: multi_row_multi_column
    sql: watchers
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    merge_series: watchers
  - name: New and episodic PR contributors
    series_name_or_func: multi_row_multi_column
    sql: new_contributors
    periods: d,w,m,q,y
    aggregate: 1,28
    skip: d,w28,m28,q28,y28
    merge_series: new_contributors
  - name: New and episodic PR contributors
    series_name_or_func: multi_row_multi_column
    sql: episodic_contributors
    periods: d,w,m,q,y
    aggregate: 1,28
    skip: d,w28,m28,q28,y28
    merge_series: episodic_contributors
  - name: New and episodic issue creators
    series_name_or_func: multi_row_multi_column
    sql: new_issues
    periods: d,w,m,q,y
    aggregate: 1,28
    skip: d,w28,m28,q28,y28
    merge_series: new_issues
  - name: New and episodic issue creators
    series_name_or_func: multi_row_multi_column
    sql: episodic_issues
    periods: d,w,m,q,y
    aggregate: 1,28
    skip: d,w28,m28,q28,y28
    merge_series: episodic_issues
  - name: Issues opened/closed by SIG
    series_name_or_func: multi_row_single_column
    sql: labels_sig_kind
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    merge_series: sigm_lsk
  - name: Issues opened/closed by SIG
    series_name_or_func: multi_row_single_column
    sql: labels_sig_kind_closed
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    merge_series: iclosed_lsk
  - name: Bot commands repository groups
    series_name_or_func: multi_row_single_column
    sql: bot_commands
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: bot_commands
  - name: Open issues/PRs by milestone and repository
    series_name_or_func: multi_row_single_column
    sql: open_issues_sigs_milestones
    periods: d
    merge_series: issues_milestones
  - name: Open issues/PRs by milestone and repository
    series_name_or_func: multi_row_single_column
    sql: open_prs_sigs_milestones
    periods: d
    merge_series: prs_milestones
  - name: Developer activity counts by repositroy group
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: hist_reviewers
  - name: Developer activity counts by repositroy group
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: hist_approvers
  - name: Overall project statistics
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: project_stats
  - name: Companies table
    sql: project_company_stats
    series_name_or_func: multi_row_single_column
    histogram: true
    annotations_ranges: true
  - name: Developer activity counts by repository groups
    sql: project_developer_stats
    series_name_or_func: multi_row_single_column
    histogram: true
    annotations_ranges: true
  - name: PR workload per SIG table
    sql: pr_workload_table
    series_name_or_func: multi_row_multi_column
    histogram: true
    annotations_ranges: true
    multi_value: true
  - name: PR workload per SIG chart
    series_name_or_func: multi_row_multi_column
    sql: pr_workload
    periods: d
    multi_value: true
  - name: PR authors repository group
    series_name_or_func: multi_row_single_column
    sql: prs_authors
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
  - name: SIG mentions
    series_name_or_func: multi_row_single_column
    sql: sig_mentions
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: PRs approval repository groups
    series_name_or_func: multi_row_multi_column
    sql: prs_state
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: d,w7,m7,q7,y7
    multi_value: true
  - name: Blocked PRs repository groups
    series_name_or_func: multi_row_multi_column
    sql: prs_blocked
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: d,w7,m7,q7,y7
    multi_value: true
  - name: Company statistics by repository groups
    series_name_or_func: multi_row_multi_column
    sql: company_activity
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: company_activity
  - name: Companies contributing in repository groups
    series_name_or_func: multi_row_multi_column
    sql: num_stats
    periods: d,w,m,q
    aggregate: 1,7,28
    skip: d,w7,m7,q7,w28,m28,q28
    merge_series: num_stats
  - name: PR reviews by contributor
    series_name_or_func: multi_row_single_column
    sql: reviews_per_user
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: user_reviews
  - name: Home dashboard (must be listed last)
    series_name_or_func: events_h
    sql: events
    periods: h
