---
metrics:
  - name: Github Stats by Repository Group
    series_name_or_func: multi_row_single_column
    sql: github_stats_by_repo_groups
    periods: h,d,w,m,q,y
    aggregate: 1,7,24
    skip: h7,w7,m7,q7,y7,d24,w24,m24,q24,y24
    multi_value: true
    merge_series: gh_stats_rgrp
    #start_from: 2018-01-01T00:00:00Z
    last_hours: 8766
    drop: sgh_stats_rgrp
  - name: Github Stats by Repository
    series_name_or_func: multi_row_single_column
    sql: github_stats_by_repos
    periods: h,d,w,m,q,y
    aggregate: 1,7,24
    skip: h7,w7,m7,q7,y7,d24,w24,m24,q24,y24
    multi_value: true
    merge_series: gh_stats_r
    #start_from: 2018-01-01T00:00:00Z
    last_hours: 8766
    drop: gh_stats_r
    allow_fail: true
  - name: PR labels repository groups
    series_name_or_func: multi_row_single_column
    sql: prs_labels
    periods: d
    merge_series: prs_labels
    drop: sprs_labels
  - name: PR Time to Approve and Merge
    series_name_or_func: multi_row_multi_column
    sql: time_metrics
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    desc: time_diff_as_string
    merge_series: time_metrics
    drop: stime_metrics
  - name: PR time to engagement
    series_name_or_func: multi_row_multi_column
    sql: first_non_author_activity
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: d,w7,m7,q7,y7
    desc: time_diff_as_string
    merge_series: first_non_author
    drop: sfirst_non_author
  - name: Opened PRs age by repository group
    series_name_or_func: multi_row_multi_column
    sql: prs_age
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    desc: time_diff_as_string
    merge_series: prs_age
    drop: sprs_age
  - name: Issues age by SIG and repository group
    series_name_or_func: multi_row_multi_column
    sql: issues_age
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    desc: time_diff_as_string
    merge_series: issues_age
    drop: sissues_age
  - name: PR comments
    series_name_or_func: single_row_multi_column
    sql: pr_comments
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    drop: 'spr_comms_med;spr_comms_p85;spr_comms_p95'
  - name: Stars and forks by repository
    series_name_or_func: multi_row_multi_column
    sql: watchers_by_alias
    periods: w
    merge_series: watchers
    drop: swatchers
  - name: New and episodic PR contributors
    series_name_or_func: multi_row_multi_column
    sql: new_contributors
    periods: d,w,m,q,y
    aggregate: 1,28
    skip: d,w28,m28,q28,y28
    merge_series: new_contributors
    drop: snew_contributors
  - name: New and episodic PR contributors
    series_name_or_func: multi_row_multi_column
    sql: episodic_contributors
    periods: d,w,m,q,y
    aggregate: 1,28
    skip: d,w28,m28,q28,y28
    merge_series: episodic_contributors
    drop: sepisodic_contributors
  - name: New and episodic issue creators
    series_name_or_func: multi_row_multi_column
    sql: new_issues
    periods: d,w,m,q,y
    aggregate: 1,28
    skip: d,w28,m28,q28,y28
    merge_series: new_issues
    drop: snew_issues
  - name: New and episodic issue creators
    series_name_or_func: multi_row_multi_column
    sql: episodic_issues
    periods: d,w,m,q,y
    aggregate: 1,28
    skip: d,w28,m28,q28,y28
    merge_series: episodic_issues
    drop: sepisodic_issues
  - name: Issues opened/closed by SIG
    series_name_or_func: multi_row_single_column
    sql: labels_sig_kind
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    merge_series: sigm_lsk
    drop: ssigm_lsk
  - name: Issues opened/closed by SIG
    series_name_or_func: multi_row_single_column
    sql: labels_sig_kind_closed
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    merge_series: iclosed_lsk
    drop: siclosed_lsk
  - name: Bot commands repository groups
    series_name_or_func: multi_row_single_column
    sql: bot_commands
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: bot_commands
    drop:  sbot_commands
  - name: Open issues/PRs by milestone and repository
    series_name_or_func: multi_row_single_column
    sql: open_issues_sigs_milestones
    periods: d
    merge_series: issues_milestones
    drop: sissues_milestones
  - name: Open issues/PRs by milestone and repository
    series_name_or_func: multi_row_single_column
    sql: open_prs_sigs_milestones
    periods: d
    merge_series: prs_milestones
    drop: sprs_milestones
  - name: Developer activity counts by repositroy group
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sqls: [hist_reviewers, hist_approvers, project_developer_stats]
    merge_series: hdev
    env:
      GHA2DB_NCPUS?: 8
  - name: Overall project statistics
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: project_stats
    merge_series: pstat
  - name: Companies table
    sql: project_company_stats
    series_name_or_func: multi_row_single_column
    histogram: true
    annotations_ranges: true
    merge_series: hcom
  - name: PR workload per SIG table
    sql: pr_workload_table
    series_name_or_func: multi_row_multi_column
    histogram: true
    annotations_ranges: true
    multi_value: true
  - name: PR workload per SIG chart
    series_name_or_func: multi_row_multi_column
    sql: pr_workload
    periods: d
    multi_value: true
    drop: 'ssig_pr_wlabs;ssig_pr_wliss;ssig_pr_wlrel;ssig_pr_wlrev'
  - name: PR authors repository group
    series_name_or_func: multi_row_single_column
    sql: prs_authors
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    merge_series: pr_auth
    drop: spr_auth
  - name: SIG mentions
    series_name_or_func: multi_row_single_column
    sql: sig_mentions
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    drop: ssigm_txt
  - name: PRs approval repository groups
    series_name_or_func: multi_row_multi_column
    sql: prs_state
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: d,w7,m7,q7,y7
    multi_value: true
    drop: 'spr_apprappr;spr_apprwait'
  - name: Blocked PRs repository groups
    series_name_or_func: multi_row_multi_column
    sql: prs_blocked
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: d,w7,m7,q7,y7
    multi_value: true
    drop: 'sprblckall;sprblckdo_not_merge;sprblckneeds_ok_to_test;sprblckno_approve;sprblckno_lgtm;sprblckrelease_note_label_needed'
  - name: Company statistics by repository groups
    series_name_or_func: multi_row_multi_column
    sqls: [company_activity, company_activity_commits]
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: company_activity
    drop: scompany_activity
  - name: Companies contributing in repository groups
    series_name_or_func: multi_row_multi_column
    sql: num_stats
    periods: d,w,m,q
    aggregate: 1,7,28
    skip: d,w7,m7,q7,w28,m28,q28
    merge_series: num_stats
    drop: snum_stats
  - name: PR reviews by contributor
    series_name_or_func: multi_row_single_column
    sql: reviews_per_user
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: user_reviews
    drop: suser_reviews
    allow_fail: true
  - name: Countries stats
    series_name_or_func: multi_row_multi_column
    sqls: [countries, committers_countries]
    periods: w,m,q,y,y2,y3,y5
    multi_value: true
    merge_series: countries
    drop: scountries
  - name: Countries stats cumulative
    series_name_or_func: multi_row_multi_column
    sqls: [countries_cum, committers_countries_cum]
    periods: m
    multi_value: true
    merge_series: countriescum
    drop: scountriescum
    env:
      GHA2DB_NCPUS?: 8
  - name: Contributor statistics
    series_name_or_func: multi_row_single_column
    sql: new_contributors_data
    custom_data: true
    merge_series: new_contributors_data
    periods: d
    drop: snew_contributors_data
  - name: Company PRs in repository groups
    sql: company_prs
    series_name_or_func: company_prs
    histogram: true
    annotations_ranges: true
  - name: PRs opened by SIG
    series_name_or_func: multi_row_single_column
    sql: prs_open_by_sig
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    drop: ssig_prs_open
  - name: Awaiting PRs by SIG
    series_name_or_func: multi_row_multi_column
    sql: awaiting_prs_by_sig
    periods: d
    multi_value: true
    drop: 'sawaiting_prs_by_sigd10;sawaiting_prs_by_sigd30;sawaiting_prs_by_sigd60;sawaiting_prs_by_sigd90;sawaiting_prs_by_sigy'
  - name: PR labels by SIG
    series_name_or_func: multi_row_single_column
    sql: prs_labels_by_sig
    periods: d
    merge_series: prs_labels_by_sig
    drop: sprs_labels_by_sig
  - name: Inactive PRs by SIG
    series_name_or_func: multi_row_multi_column
    sql: inactive_prs_by_sig
    periods: d
    multi_value: true
    drop: 'sinactive_prs_by_sigw2;sinactive_prs_by_sigd30;sinactive_prs_by_sigd90'
    env:
      GHA2DB_NCPUS?: 8
  - name: Inactive issues by SIG
    series_name_or_func: multi_row_multi_column
    sql: inactive_issues_by_sig
    periods: d
    multi_value: true
    drop: 'sinactive_issues_by_sigw2;sinactive_issues_by_sigd30;sinactive_issues_by_sigd90'
    env:
      GHA2DB_NCPUS?: 8
  - name: Contributions chart
    series_name_or_func: multi_row_multi_column
    sqls: [reviewers, approvers, committers, contributors]
    periods: d,w,m
    aggregate: 1,7
    skip: d,w7,m7
    merge_series: cs
    drop: scs
    project: kubernetes
    env:
      GHA2DB_NCPUS?: 8
  - name: Home dashboard (must be listed last)
    series_name_or_func: events_h
    sql: events
    periods: h
    drop: sevents_h
