---
tags:
  - name: Companies
    sql: companies_tags
    series_name: companies
    name_tag: companies_name
  - name: Country names
    sql: countries_tags
    series_name: countries
    name_tag: country_name
  - name: Timezone offsets
    sql: tz_offset_tags
    series_name: tz_offsets
    name_tag: tz_offset
