---
tags:
  - name: Repository aliases
    sql: repo_aliases_tags
    series_name: all_repo_names
    name_tag: all_repo_names_name
    value_tag: all_repo_names_value
  - name: Repository aliases (top N)
    sql: top_repo_aliases_tags
    series_name: top_repo_names
    name_tag: top_repo_names_name
    value_tag: top_repo_names_value
  - name: Repository aliases (top N + All)
    sql: top_repo_aliases_tags_with_all
    series_name: top_repo_names_with_all
    name_tag: top_repo_names_name_with_all
    value_tag: top_repo_names_value_with_all
  - name: Repository groups including All combined
    sql: repo_groups_tags_with_all_combined
    series_name: all_combined_repo_groups
    name_tag: all_combined_repo_group_name
    value_tag: all_combined_repo_group_value
  - name: Repository groups including All
    sql: repo_groups_tags_with_all
    series_name: all_repo_groups
    name_tag: all_repo_group_name
    value_tag: all_repo_group_value
  - name: Repository groups without All
    sql: repo_groups_tags
    series_name: repo_groups
    name_tag: repo_group_name
    value_tag: repo_group_value
  - name: Repository names (top N + All)
    sql: top_repos_tags_with_all
    series_name: top_repos_with_all
    name_tag: top_repos_name_with_all
    value_tag: top_repos_value_with_all
  - name: Companies
    sql: companies_tags
    series_name: companies
    name_tag: companies_name
  - name: Bot commands
    sql: bot_commands_tags
    series_name: bot_commands
    name_tag: bot_command_name
    # other_tags:
    #   alias: full_command
  - name: SIG mentions using texts
    sql: sig_mentions_texts_tags
    series_name: sig_mentions_texts
    name_tag: sig_mentions_texts_name
    value_tag: sig_mentions_texts_value
  - name: SIG mentions using labels
    sql: sig_mentions_labels_sigs_tags
    series_name: sig_mentions_labels
    name_tag: sig_mentions_labels_name
    value_tag: sig_mentions_labels_value
  - name: SIG mentions categories using labels
    sql: sigm_lbl_kinds_tags
    series_name: sigm_lbl_kinds
    name_tag: sigm_lbl_kind_name
    value_tag: sigm_lbl_kind_value
  - name: SIG mentions using labels with All
    sql: sig_mentions_labels_sigs_tags_with_all
    series_name: sig_mentions_labels_with_all
    name_tag: sig_mentions_labels_name_with_all
    value_tag: sig_mentions_labels_value_with_all
  - name: SIG mentions categories using labels with all
    sql: sigm_lbl_kinds_tags_with_all
    series_name: sigm_lbl_kinds_with_all
    name_tag: sigm_lbl_kind_name_with_all
    value_tag: sigm_lbl_kind_value_with_all
  - name: Priority labels with all
    sql: labels_priorities_tags_with_all
    series_name: priority_labels_with_all
    name_tag: priority_labels_name_with_all
    value_tag: priority_labels_value_with_all
  - name: Size labels with all
    sql: labels_sizes_tags_with_all
    series_name: size_labels_with_all
    name_tag: size_labels_name_with_all
    value_tag: size_labels_value_with_all
  - name: Milestones
    sql: milestones_tags_with_all
    series_name: all_milestones
    name_tag: all_milestones_name
    value_tag: all_milestones_value
  - name: Reviewers
    sql: reviewers_tags
    series_name: reviewers
    name_tag: reviewers_name
  - name: PR labels
    sql: pr_labels_tags
    series_name: pr_labels_tags
    name_tag: pr_labels_tags_name
    value_tag: pr_labels_tags_value
  - name: Users
    sql: users_tags
    series_name: users
    name_tag: users_name
  - name: Country names
    sql: countries_tags
    series_name: countries
    name_tag: country_name
  - name: Cumulative periods
    sql: cumulative_periods
    series_name: cumperiods
    name_tag: cumperiod_name
  - name: Timezone offsets
    sql: tz_offset_tags
    series_name: tz_offsets
    name_tag: tz_offset
