---
vars:
  - name: os_hostname
    type: s
    command: [hostname]
  - name: full_name
    type: s
    value: Kubernetes
  - name: projects_partial_html
    type: s
    command:
      - cat
      - '{{datadir}}partials/projects.html'
    replaces:
      - [hostname, os_hostname]
      #- [hostname, ':devstats.cncf.io']
      - [':testsrv=cncftest.io ', ':']
      - [': cncftest.io=testsrv', ':']
      - [':testsrv=', ':<!-- ']
      - [':=testsrv', ': -->']
      - [':prodsrv=devstats.cncf.io ', ':']
      - [': devstats.cncf.io=prodsrv', ':']
      - [':prodsrv=', ':<!-- ']
      - [':=prodsrv', ': -->']
  - name: dashboards_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/dashboards.md'
    replaces:
      - [hostname, os_hostname]
      - [full_name, full_name]
      - [proj_name, $GHA2DB_PROJECT]
      - [url_prefix, ':k8s']
  - name: gh_stats_commits_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/gh_stats_commits.md'
    replaces:
      - [full_name, full_name]
  - name: gh_stats_iclosed_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/gh_stats_iclosed.md'
    replaces:
      - [full_name, full_name]
  - name: gh_stats_iopened_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/gh_stats_iopened.md'
    replaces:
      - [full_name, full_name]
  - name: gh_stats_propened_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/gh_stats_propened.md'
    replaces:
      - [full_name, full_name]
  - name: gh_stats_prmerged_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/gh_stats_prmerged.md'
    replaces:
      - [full_name, full_name]
  - name: gh_stats_prclosed_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/gh_stats_prclosed.md'
    replaces:
      - [full_name, full_name]
  - name: gh_stats_prcomments_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/gh_stats_prcomments.md'
    replaces:
      - [full_name, full_name]
  - name: gh_stats_prcommenters_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/gh_stats_prcommenters.md'
  - name: gh_stats_icomments_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/gh_stats_icomments.md'
  - name: gh_stats_icommenters_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/gh_stats_icommenters.md'
    replaces:
      - [full_name, full_name]
  - name: gh_stats_reviewers_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/gh_stats_reviewers.md'
    replaces:
      - [full_name, full_name]
  - name: sig_mentions_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/sig_mentions.md'
    replaces:
      - [full_name, full_name]
  - name: pr_reviews_by_contributor_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/pr_reviews_by_contributor.md'
    replaces:
      - [full_name, full_name]
  - name: pr_workload_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/pr_workload.md'
    replaces:
      - [full_name, full_name]
  - name: blocked_prs_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/blocked_prs.md'
    replaces:
      - [full_name, full_name]
  - name: bot_commands_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/bot_commands.md'
    replaces:
      - [full_name, full_name]
  - name: sig_milestones_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/sig_milestones.md'
    replaces:
      - [full_name, full_name]
  - name: contrib_comps_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/contributing_companies.md'
    replaces:
      - [full_name, full_name]
  - name: companies_table_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/companies_table.md'
    replaces:
      - [full_name, full_name]
  - name: company_stats_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/company_stats.md'
    replaces:
      - [full_name, full_name]
  - name: developer_stats_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/developer_stats.md'
    replaces:
      - [full_name, full_name]
  - name: issues_age_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/issues_age.md'
    replaces:
      - [full_name, full_name]
  - name: issues_opened_closed_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/issues_opened_closed.md'
    replaces:
      - [full_name, full_name]
  - name: episodic_issues_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/episodic_issues.md'
    replaces:
      - [full_name, full_name]
  - name: episodic_prs_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/episodic_prs.md'
    replaces:
      - [full_name, full_name]
