---
projects:
  envoy:
    order: 1
    name: Envoy
    status: Incubating
    command_line:
      - envoyproxy
    start_date: 2016-09-14T00:00:00Z
    # start_date: 2019-12-01T00:00:00Z # override
    join_date: 2017-09-13T00:00:00Z
    psql_db: envoy
    shared_db: allprj
    main_repo: envoyproxy/envoy
    annotation_regexp: '^v\d+\.\d+\.0$'
    files_skip_pattern: '(^|/)_?(vendor|Godeps|_workspace)/'
