---
projects:
  envoy:
    order: 0
    name: Envoy
    status: Incubating
    command_line:
      - envoyproxy
    start_date: 2016-09-14T00:00:00Z
    # start_date: 2019-12-01T00:00:00Z # override
    join_date: 2017-09-13T00:00:00Z
    psql_db: envoy
    main_repo: envoyproxy/envoy
    annotation_regexp: '^v\d+\.\d+\.0$'
    files_skip_pattern: '(^|/)_?(vendor|Godeps|_workspace)/'
  lfn:
    order: 1
    name: Linux Foundation Networking
    status: "-"
    command_line:
      - 'iovisor,mininet,opennetworkinglab,opensecuritycontroller,open-switch,p4lang,OpenBMP,tungstenfabric,opencord'
    start_date: 2014-01-02T00:00:00Z
    start_date: 2018-12-01T00:00:00Z # override
    join_date: null
    psql_db: lfn
    main_repo: 'iovisor/bcc'
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: ''
  iovisor:
    order: 2
    name: IO Visor
    status: "-"
    command_line:
      - iovisor
    start_date: 2015-06-05T00:00:00Z
    start_date: 2018-12-01T00:00:00Z # override
    join_date: null
    psql_db: iovisor
    shared_db: lfn
    main_repo: 'iovisor/bcc'
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: ''
  mininet:
    order: 3
    name: Mininet
    status: "-"
    command_line:
      - mininet
    start_date: 2014-01-02T00:00:00Z
    start_date: 2018-12-01T00:00:00Z # override
    join_date: null
    psql_db: mininet
    shared_db: lfn
    main_repo: 'mininet/mininet'
    annotation_regexp: '^\d+\.\d+\.\d+'
    files_skip_pattern: ''
  opennetworkinglab:
    order: 4
    name: Open Networking Laboratory
    status: "-"
    command_line:
      - opennetworkinglab
    start_date: 2014-12-05T00:00:00Z
    start_date: 2018-12-01T00:00:00Z # override
    join_date: null
    psql_db: opennetworkinglab
    shared_db: lfn
    main_repo: 'opennetworkinglab/onos'
    annotation_regexp: '^\d+\.\d+\.\d+$'
    files_skip_pattern: ''
  opensecuritycontroller:
    order: 5
    name: Open Security Controller
    status: "-"
    command_line:
      - opensecuritycontroller
    start_date: 2017-06-28T00:00:00Z
    start_date: 2018-12-01T00:00:00Z # override
    join_date: null
    psql_db: opensecuritycontroller
    shared_db: lfn
    main_repo: 'opensecuritycontroller/osc-core'
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: ''
    #disabled: true
  openswitch:
    order: 6
    name: OpenSwitch
    status: "-"
    command_line:
      - 'open-switch'
    start_date: 2016-12-23T00:00:00Z
    start_date: 2018-11-28T00:00:00Z # override
    join_date: null
    psql_db: openswitch
    shared_db: lfn
    main_repo: 'open-switch/opx-nas-interface'
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: ''
  p4lang:
    order: 7
    name: P4 Language
    status: "-"
    command_line:
      - p4lang
    start_date: 2016-12-17T00:00:00Z
    start_date: 2018-12-01T00:00:00Z # override
    join_date: null
    psql_db: p4lang
    shared_db: lfn
    main_repo: 'p4lang/p4c'
    annotation_regexp: ''
    files_skip_pattern: ''
  openbmp:
    order: 8
    name: OpenBMP
    status: "-"
    command_line:
      - OpenBMP
    start_date: 2015-01-02T00:00:00Z
    start_date: 2018-12-01T00:00:00Z # override
    join_date: null
    psql_db: openbmp
    shared_db: lfn
    main_repo: 'OpenBMP/openbmp'
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: ''
  tungstenfabric:
    order: 9
    name: Tungsten Fabric
    status: "-"
    command_line:
      - tungstenfabric
    start_date: 2018-03-20T00:00:00Z
    start_date: 2018-11-29T00:00:00Z # override
    join_date: null
    psql_db: tungstenfabric
    shared_db: lfn
    main_repo: 'tungstenfabric/website'
    annotation_regexp: ''
    files_skip_pattern: ''
  cord:
    order: 10
    name: CORD
    status: "-"
    command_line:
      - opencord
    start_date: 2016-06-01T00:00:00Z
    start_date: 2018-12-01T00:00:00Z # override
    join_date: null
    psql_db: cord
    shared_db: lfn
    main_repo: 'opencord/voltha'
    annotation_regexp: '^\d+\.\d+\.\d+$'
    files_skip_pattern: ''
  zephyr:
    order: 11
    name: Zephyr
    status: "-"
    command_line:
      - zephyrproject-rtos
    start_date: 2016-05-26T00:00:00Z
    start_date: 2018-12-01T00:00:00Z # override
    join_date: null
    psql_db: zephyr
    main_repo: zephyrproject-rtos/zephyr
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: ''
  linux:
    order: 12
    name: Linux
    status: "-"
    command_line:
      - torvalds
      - linux
    start_date: 2012-07-01T00:00:00Z
    start_date: 2018-12-01T00:00:00Z # override
    join_date: null
    psql_db: linux
    main_repo: torvalds/linux
    annotation_regexp: '^v(\d+\.){1,2}\d+$'
    files_skip_pattern: ''
